misc: smpro-errmon: Fix wrong functions return type
When compile with -Werror=incompatible-pointer-types, multiple errors
as below appear due to wrong return type of the xxx_show() function.
This commit to fix the issue.

drivers/misc/smpro-errmon.c:430:23: error: initialization of 'ssize_t
(*)(struct device *, struct device_attribute *, char *)' {aka 'long int
(*)(struct device *, struct device_attribute *, char *)'} from
incompatible pointer type 'int (*)(struct device *, struct
device_attribute *, char *)' [-Werror=incompatible-pointer-types]

Signed-off-by: Quan Nguyen <qnguyen@amperecomputing.com>