misc: smpro-misc: Fix wrong functions return type
When compile with -Werror=incompatible-pointer-types, multiple errors
as below appear due to wrong return type of the pair xxx_show/store()
functions. This commit to fix the issue.

../drivers/misc/smpro-misc.c:122:23: error: initialization of 'ssize_t
(*)(struct device *, struct device_attribute *, const char *, size_t)'
{aka 'long int (*)(struct device *, struct device_attribute *, const
char *, long unsigned int)'} from incompatible pointer type 'int
(*)(struct device *, struct device_attribute *, const char *, size_t)'
{aka 'int (*)(struct device *, struct device_attribute *, const char *,
long unsigned int)'} [-Werror=incompatible-pointer-types]

Signed-off-by: Quan Nguyen <qnguyen@amperecomputing.com>